services:
  app:
    build:
      context: .
    ports:
      - "8080:8080" # 必要に応じて変更
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=your_user
      - DB_PASSWORD=your_password
      - DB_NAME=your_db
      - USE_SSL=false
    depends_on:
      - db
    # 開発環境向けのボリュームマッピング（必要に応じて）
    # volumes:
    #   - .:/app

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_db
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306" # 必要に応じて変更
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
